title: the long loneliness
description: i created this repo to share the feeling of loneliness for human beings. but, furthermore, i also hope one day a warm community would be formed to comfort the lonely hearts all around the world.
version: 1.0.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
